/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as HourlyRouteImport } from './routes/hourly'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as MonthlyRouteImport } from './routes/monthly'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as DevKitchenRouteImport } from './routes/dev/kitchen'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const HourlyRoute = HourlyRouteImport.update({
  id: '/hourly',
  path: '/hourly',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const MonthlyRoute = MonthlyRouteImport.update({
  id: '/monthly',
  path: '/monthly',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const DevKitchenRoute = DevKitchenRouteImport.update({
  id: '/dev/kitchen',
  path: '/dev/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/daily': typeof DailyRoute
  '/hourly': typeof HourlyRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/monthly': typeof MonthlyRoute
  '/sessions': typeof SessionsRoute
  '/stats': typeof StatsRoute
  '/usage': typeof UsageRoute
  '/dev/kitchen': typeof DevKitchenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/daily': typeof DailyRoute
  '/hourly': typeof HourlyRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/monthly': typeof MonthlyRoute
  '/sessions': typeof SessionsRoute
  '/stats': typeof StatsRoute
  '/usage': typeof UsageRoute
  '/dev/kitchen': typeof DevKitchenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/daily': typeof DailyRoute
  '/hourly': typeof HourlyRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/monthly': typeof MonthlyRoute
  '/sessions': typeof SessionsRoute
  '/stats': typeof StatsRoute
  '/usage': typeof UsageRoute
  '/dev/kitchen': typeof DevKitchenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/daily'
    | '/hourly'
    | '/login'
    | '/models'
    | '/monthly'
    | '/sessions'
    | '/stats'
    | '/usage'
    | '/dev/kitchen'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/daily'
    | '/hourly'
    | '/login'
    | '/models'
    | '/monthly'
    | '/sessions'
    | '/stats'
    | '/usage'
    | '/dev/kitchen'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/daily'
    | '/hourly'
    | '/login'
    | '/models'
    | '/monthly'
    | '/sessions'
    | '/stats'
    | '/usage'
    | '/dev/kitchen'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  DailyRoute: typeof DailyRoute
  HourlyRoute: typeof HourlyRoute
  LoginRoute: typeof LoginRoute
  ModelsRoute: typeof ModelsRoute
  MonthlyRoute: typeof MonthlyRoute
  SessionsRoute: typeof SessionsRoute
  StatsRoute: typeof StatsRoute
  UsageRoute: typeof UsageRoute
  DevKitchenRoute: typeof DevKitchenRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hourly': {
      id: '/hourly'
      path: '/hourly'
      fullPath: '/hourly'
      preLoaderRoute: typeof HourlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monthly': {
      id: '/monthly'
      path: '/monthly'
      fullPath: '/monthly'
      preLoaderRoute: typeof MonthlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/kitchen': {
      id: '/dev/kitchen'
      path: '/dev/kitchen'
      fullPath: '/dev/kitchen'
      preLoaderRoute: typeof DevKitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  DailyRoute: DailyRoute,
  HourlyRoute: HourlyRoute,
  LoginRoute: LoginRoute,
  ModelsRoute: ModelsRoute,
  MonthlyRoute: MonthlyRoute,
  SessionsRoute: SessionsRoute,
  StatsRoute: StatsRoute,
  UsageRoute: UsageRoute,
  DevKitchenRoute: DevKitchenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
